# run models without estimation
name: call-run-ss3-with-est
on: 
  push:
    paths:
    - '**.tpl'
  pull_request:
    paths:
      - '**.tpl'
  workflow_dispatch:
jobs:
  call-workflow:
    uses: nmfs-stock-synthesis/workflows/.github/workflows/run-ss3-with-est.yml@main